---
title: "summarystats"
format: html
---

```{r}
library(dplyr)
library(randomForest)
library(rfPermute)
library(vegan)
library(ggplot2)
library(readxl)
library(tidyr)
library(ggpubr)
```

```{r}

feats_with_classes <- read_excel("C:/Users/priya/Downloads/Ty_superset_metabolites.xlsx")
```

```{r}
write.csv(feats_with_classes, file = "all_feat_classes.cv")
```

```{r}

num_df_final_id <- oculina_final[, c(6, 40:16396)]
  
```

```{r}
```

```{r}
Oculina_long <- num_df_final_id |>
  pivot_longer(-id,
               names_to = "Metabolite",
               values_to = "Abundance")
```

```{r}
Oculina_joined <- Oculina_long %>%
  left_join(feats_with_classes %>%
              select(metabolite, compound_class),
            by = c("Metabolite" = "metabolite"))
```

```{r}
Oculina_class <- Oculina_joined %>%
  group_by(id, compound_class) %>%
  summarise(Total_Abundance = sum(Abundance, na.rm = TRUE),
            .groups = "drop")
```

```{r}
Oculina_class_wide <- Oculina_class %>%
  pivot_wider(names_from = compound_class,
              values_from = Total_Abundance)
            #  values_fill = 0)
```

```{r}

# ocu_final_anno <-
#   num_df_final |>
#   select(where(colnames IN feats_with_classes AND feats_with_classes(coraldb_compound_name))) NOT  NULL)
# 
# num_df_final |>
#   summarise(feat_total = [], total_annotated = 
```

```{r}
superset_feats_annotated <-
  feats_with_classes |>
  filter(coraldb_compound_name != 'NA')
```

```{r}
Ocu_joined_anno <- Oculina_long %>%
  right_join(superset_feats_annotated %>%
              select(metabolite, compound_class, coraldb_compound_name, origin),
            by = c("Metabolite" = "metabolite"))
```

```{r}
Ocu_wide_anno <- Ocu_joined_anno %>%
  pivot_wider(-c(compound_class, coraldb_compound_name, origin),
              names_from = Metabolite,
              values_from = Abundance) 
```

entropy, richness, evenness:

```{r}
write.csv(ocu_fin_div, file = "oculina_final_diversity.csv")
```

```{r}
ocu_fin_div <- read.csv("oculina_final_diversity.csv")

ocu_fin_div <- ocu_fin_div |>
  mutate(Phenotype = bleaching) |>
    mutate(Phenotype = recode(Phenotype,
                              "B" = "Aposymbiotic",
                              "NB" = "Symbiotic"))

ggplot(ocu_fin_div, aes(x = Phenotype, y = Richness, fill = Phenotype)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c("Aposymbiotic" = "orange", "Symbiotic" = "blue")) +
  theme_minimal() +
   geom_point(
    position = position_jitterdodge(
      jitter.width = 0.2,   # stay within each box
      jitter.height = 0,
      dodge.width  = 1,     
    ), 
    
    shape = 21,               # fill + outline
    color = "black",          # outline
    stroke = 0.45,
    size = 1,
    alpha = 0.8
  ) +
  
  stat_compare_means(aes(group = Phenotype), 
                     method = "kruskal.test", 
                     label = "p.format",
                     ) 
```

```{r}
ggplot(ocu_fin_div, aes(x = Phenotype, y = Entropy, fill = Phenotype)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c("Aposymbiotic" = "orange", "Symbiotic" = "blue")) +
  theme_minimal() +
   geom_point(
    position = position_jitterdodge(
      jitter.width = 0.2,   # stay within each box
      jitter.height = 0,
      dodge.width  = 1,
      #seed = 1,
    ), 
    
    shape = 21,               # fill + outline
    color = "black",          # outline
    stroke = 0.45,
    size = 1,
    alpha = 0.8
  ) +
  
  stat_compare_means(aes(group = Phenotype), 
                     method = "kruskal.test", 
                     label = "p.format",
                     ) 
```

```{r}
ggplot(ocu_fin_div, aes(x = Phenotype, y = Evenness, fill = Phenotype)) +
  geom_boxplot(outlier.shape = NA) +
  scale_fill_manual(values = c("Aposymbiotic" = "orange", "Symbiotic" = "blue")) +
  theme_minimal() +
   geom_point(
    position = position_jitterdodge(
      jitter.width = 0.2,   # stay within each box
      jitter.height = 0,
      dodge.width  = 1,
      #seed = 1,
    ), 
    
    shape = 21,               # fill + outline
    color = "black",          # outline
    stroke = 0.45,
    size = 1,
    alpha = 0.8
  ) +
  
  stat_compare_means(aes(group = Phenotype), 
                     method = "kruskal.test", 
                     label = "p.format",
                     ) 
```

diversity box plots with depth_sa as the three categories of box plots

```{r}
ocu_fin_div_depthsa <- ocu_fin_div |>
  full_join(oculina_final[, c(6,16426)]) 

ocu_fin_div_depthsa <- ocu_fin_div_depthsa[-c(20, 26, 39, 41, 47, 64, 66, 73, 75),]
```

```{r}
# Fit ANOVA and Tukey test
evenness_model <- aov(Evenness ~ depth_sa, data = ocu_fin_div_depthsa)
evenness_tukey <- TukeyHSD(evenness_model)

# Extract letters using multcompView or agricolae
# Example using multcomp

#library(multcomp)
evenness_cld <- glht(evenness_model, linfct = mcp(depth_sa = "Tukey"))
evenness_cld_res <- cld(evenness_cld)
evenness_letters_df <- data.frame(
  group = names(evenness_cld_res$mcletters$Letters),
                         letter = evenness_cld_res$mcletters$Letters)
```

```{r}

ocu_fin_div_depthsa <- ocu_fin_div_depthsa |>
  filter(!is.na(depth_sa))
ggplot(ocu_fin_div_depthsa, aes(x = depth_sa, y = Evenness, fill = depth_sa)) +
  geom_boxplot(outlier.shape = NA) +
  
  scale_fill_manual(values = c("Shallow Aposymbiotic" = "orange", "Shallow Symbiotic" = "blue", "Deep Aposymbiotic" = "tomato3")) +
  
  theme_minimal() +
   geom_point(
    position = position_jitterdodge(
      jitter.width = 0.2,   # stay within each box
      jitter.height = 0,
      dodge.width  = 1,     
    ), 
    
    shape = 21,               # fill + outline
    color = "black",          # outline
    stroke = 0.45,
    size = 1,
    alpha = 0.8
  ) +
  
  stat_compare_means(aes(group = depth_sa), 
                     method = "kruskal.test", 
                     label = "p.format",
                     ) 
```

```{r}
# of "oculina_final.csv"
# ; symbiont / mL
# ; chlorophyll/


ocu_final <- read.csv("../Data/Metabolomics/oculina_final.csv")
```

```{r}

ocu_fin_div_physio <- ocu_fin_div |>
 left_join(ocu_final[,c(6, 16405, 16421, 16422, 16426)], join_by(sample_id == id))
```

```{r}

model_chl_rich <- lm(ug_chla_cm ~ Richness, data = ocu_fin_div_physio)
r_squared_chl_rich <- summary(model_chl_rich)$r.squared

r2_label_chl_rich <- paste0("R^2 = ", round(r_squared_chl_rich, 3))


ggplot(ocu_fin_div_physio, aes(x = Richness, y = ug_chla_cm, color = depth_sa)) +
  geom_point() +
  
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  
  stat_cor(aes(group = 1), method = "pearson", label.x.npc = "left", label.y.npc = "top") + # Adds R and p-value
  
 #annotate("text", label = r2_label_sym_rich, x = -Inf, y = Inf, size = 5, hjust = -0.1, vjust = 1.1) +
  
  scale_color_manual(values = c("Shallow Aposymbiotic" = "orange", "Shallow Symbiotic" = "blue", "Deep Aposymbiotic" = "tomato3")) +
theme_classic(base_size = 14) +
  theme(plot.margin=ggplot2::margin(t=5,b=2,r=5,l=5,unit="pt"),
        ) 

  
```

```{r}

model_sym_rich <- lm(sym_cm2 ~ Richness, data = ocu_fin_div_physio)
r_squared_sym_rich <- summary(model_sym_rich)$r.squared

r2_label_sym_rich <- paste0("R^2 = ", round(r_squared_sym_rich, 3))


ggplot(ocu_fin_div_physio, aes(x = Richness, y = sym_cm2, color = depth_sa)) +
  geom_point() +
  
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  
  stat_cor(aes(group = 1), method = "pearson", label.x.npc = "left", label.y.npc = "top") + # Adds R and p-value
  
 #annotate("text", label = r2_label_sym_rich, x = -Inf, y = Inf, size = 5, hjust = -0.1, vjust = 1.1) +
  
  scale_color_manual(values = c("Shallow Aposymbiotic" = "orange", "Shallow Symbiotic" = "blue", "Deep Aposymbiotic" = "tomato3"))
```

```{r}

model_chl_ent <- lm(chla_pg_sym ~ Entropy, data = ocu_fin_div_physio)
r_squared_chl_ent <- summary(model_chl_ent)$r.squared

r2_label_chl_ent <- paste0("R^2 = ", round(r_squared_chl_ent, 3))


ggplot(ocu_fin_div_physio, aes(x = Entropy, y = chla_pg_sym, color = depth_sa)) +
  geom_point() +
  
   geom_smooth(method = "lm", se = FALSE, color = "black") +
  
  stat_cor(method = "pearson", label.x.npc = "left", label.y.npc = "top") + # Adds R and p-value
  
 #annotate("text", label = r2_label_sym_rich, x = -Inf, y = Inf, size = 5, hjust = -0.1, vjust = 1.1) +
  
  scale_color_manual(values = c("Shallow Aposymbiotic" = "orange", "Shallow Symbiotic" = "blue", "Deep Aposymbiotic" = "tomato3"))
```

```{r}

model_sym_ent <- lm(sym_cm2 ~ Entropy, data = ocu_fin_div_physio)
r_squared_sym_ent <- summary(model_sym_ent)$r.squared

r2_label_sym_ent <- paste0("R^2 = ", round(r_squared_chl_ent, 3))


ggplot(ocu_fin_div_physio, aes(x = Entropy, y = sym_cm2, color = depth_sa)) +
  geom_point() +
  
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  
  stat_cor(method = "pearson", label.x.npc = "left", label.y.npc = "top") + # Adds R and p-value
  
 #annotate("text", label = r2_label_sym_rich, x = -Inf, y = Inf, size = 5, hjust = -0.1, vjust = 1.1) +
  
  scale_color_manual(values = c("Shallow Aposymbiotic" = "orange", "Shallow Symbiotic" = "blue", "Deep Aposymbiotic" = "tomato3")) +
  theme_classic(base_size = 14) +
  theme(plot.margin=ggplot2::margin(t=5,b=2,r=5,l=5,unit="pt"),
        ) 

```
